### ISSUE TITLE
alignment issue in grub-core/lib/gpt.c

### ISSUE THREAD

**Issue by GangHoyong** [coreos/grub#11]
OS : Yosemite 10.10.4
sudo make check -> compile time error 

grub-core/lib/gpt.c:140:30: error: cast from 'unsigned char *' to 'grub_uint32_t *' (aka 'unsigned int *') increases required alignment from
      1 to 4 [-Werror,-Wcast-align]
  *crc = grub_swap_bytes32 (*(grub_uint32_t *)
                             ^~~~~~~~~~~~~~~~~

**Comment by marineam** [comment]
What compiler are you using?

**Comment by marineam** [comment]
Posted a PR that hopefully resolves your issue: https://github.com/coreos/grub/pull/13
