### ISSUE TITLE
Disable FSCK on boot

### ISSUE THREAD

**Issue by remonlam** [coreos/grub#12]
Hi,

Perhaps I'm posting this in the wrong place but because the question is related to GRUB this seems the best place.

I've tried to add the "fastboot" option in the GRUB config to prevent CoreOS from checking the filesystem on boot. However this option does not work.

Why I want to do this? I'm running CoreOS on a Minnowboard Max that does not have a proper working RTC so when the power is disconnected the time is being set back to the year 2000. On boot the root partition of CoreOS will not mount because of the time changes and needs to be checked/repaired.

Is there an option to prevent CoreOS from checking the disk on boot? because there is not /etc/fstab file I came up with the idea to do this in GRUB, but cant get it to work properly.

Thanks!

**Comment by marineam** [comment]
This issue was moved to coreos/bugs#424
